paths: 
  # full path to the spectra folder containing all spectra files
  spectra_dir: '/Users/zacharymcgrath/Desktop/nod2 data/single/'
  # full path to the .fasta database file
  database_file: '/Users/zacharymcgrath/Desktop/raw_inputs/NOD2_E3/filtered_mouse_database.fasta'
  # full path to the output directory
  output_dir: '/Users/zacharymcgrath/Desktop/raw_inputs/BALB3_E3/output/'

search_params:
  # minimum length peptide to look for
  min_peptide_len: 3
  # maximum length peptide to look for
  max_peptide_len: 30
  # tolerance (in ppm) to allow when matching m/z peaks
  ppm_tolerance: 20
  # tolerance (in Da) to allow when matching precursor masses
  precursor_tolerance: 10
  
  #-----------------------------------------------------------
  # NOTE: when using the filtering options below (either the peak
  # filtering or the abundance filtering), only set 1 of the values.
  # If both are set, then it defaults to the value set for peak_filter
  #-----------------------------------------------------------
  spectra_filtering: 
    # the number of most abundant (intense) peaks to allow when filtering
    # input spectra
    num_peaks: 25
    # the minimum allowed percentage of the total intensity a peak 
    # is allowed to have to pass the filter. Values should be 
    # in the range (0, 1) 
    relative_abundance: .01

experiment_params:
  # in vitro digest performed on the sample. Leave '' if none
  digest: ''

run_parameters:
  # printing to the console during the run
  verbose: True
  # the number of cores to allow in the search. Should be a number 
  cores: 1
  # the number of alignments to keep per spectrum
  top_results: 5

dev_params:
  # Extra extra printing options for debugging the application
  debug: True
  # "truth" set json file that has the "truth" sequence for every 
  # spectrum. Should be keyed by some id param that is extracted by the tool 
  # to check where the correct value falls off at. Format of the json is simple:
  # {spectrum_id: {'sequence': str, 'hybrid': bool, 'parent': str}}
  # if the param is left blank or the file cannot be found, it is not used
  truth_set: ''